import {readdirSync, writeFileSync, statSync} from 'fs';

readdirSync(__dirname).forEach(entry => {
  if (statSync(__dirname + '/' + entry).isDirectory() && entry[0] !== '_') {
    writeFileSync(__dirname + '/' + entry + '.autogenerated.test.ts', [
      '// auto-generated test',
      '',
      'import runTest from \'./run-test\';',
      '',
      'runTest(\'' + entry + '\');',
      '',
    ].join('\n'));
  }
});