export default interface IndexOptions {
    /**
     * The write concern
     */
    readonly w?: number | string;
    /**
     * The write concern timeout
     */
    readonly wtimeout?: number;
    /**
     * Specify a journal write concern
     */
    readonly j?: boolean;
    /**
     * Creates a unique index (default: false)
     */
    readonly unique?: boolean;
    /**
     * Creates a sparse index (default: false)
     */
    readonly sparse?: boolean;
    /**
     * Creates the index in the background, yielding whenever possible (default: false)
     */
    readonly background?: boolean;
    /**
     * A unique index cannot be created on a key that has pre-existing duplicate values.
     * If you would like to create the index anyway, keeping the first document the database
     * indexes and deleting all subsequent documents that have duplicate value, set dropDups
     * to true.
     */
    readonly dropDups?: boolean;
    /**
     * For geospatial indexes set the lower bound for the co-ordinates.
     */
    readonly min?: number;
    /**
     * For geospatial indexes set the high bound for the co-ordinates.
     */
    readonly max?: number;
    /**
     * Specify the format version of the indexes.
     */
    readonly v?: number;
    /**
     * Allows you to expire data on indexes applied to a data (MongoDB 2.2 or higher)
     */
    readonly expireAfterSeconds?: number;
    /**
     * Override the autogenerated index name (useful if the resulting name is larger than 128 bytes)
     */
    readonly name?: string;
    /**
     * Creates a partial index based on the given filter object (MongoDB 3.2 or higher)
     */
    readonly partialFilterExpression?: Object;
    /**
     * Specify collation (MongoDB 3.4 or higher) settings for update operation (see 3.4 documentation for available fields).
     */
    readonly collation?: Object;
}
